// SPDX-License-Identifier: LGPL-2.1-only WITH OCaml-LGPL-linking-exception

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const CHUNK_BYTES = 256 * 1024;
const LITERAL_BYTES = 16 * 1024;

function fail(message) {
  throw new Error(message);
}

function parseArguments(argv) {
  let profile = null;
  let directory = null;
  let mode = null;
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    const value = argv[index + 1];
    if (!value) fail(`${argument} requires a value`);
    if (argument === '--profile') profile = resolve(value);
    else if (argument === '--output-dir' || argument === '--check-dir') {
      if (mode !== null) fail('--output-dir and --check-dir are mutually exclusive');
      mode = argument === '--output-dir' ? 'output' : 'check';
      directory = resolve(value);
    } else fail(`unknown argument: ${argument}`);
    index += 1;
  }
  if (profile === null || directory === null || mode === null) {
    fail('--profile and exactly one of --output-dir/--check-dir are required');
  }
  return { profile, directory, mode };
}

function moonBytes(bytes) {
  let result = 'b"';
  for (const byte of bytes) {
    if (byte === 0x22) result += '\\"';
    else if (byte === 0x5c) result += '\\\\';
    else if (byte === 0x0a) result += '\\n';
    else if (byte === 0x0d) result += '\\r';
    else if (byte === 0x09) result += '\\t';
    else if (byte >= 0x20 && byte <= 0x7e) result += String.fromCharCode(byte);
    else result += `\\x${byte.toString(16).padStart(2, '0')}`;
  }
  return `${result}"`;
}

function shardSource(index, bytes) {
  const literals = [];
  for (let offset = 0; offset < bytes.length; offset += LITERAL_BYTES) {
    literals.push(moonBytes(bytes.subarray(offset, offset + LITERAL_BYTES)));
  }
  const suffix = String(index).padStart(2, '0');
  return Buffer.from([
    '// SPDX-License-Identifier: LGPL-2.1-only WITH OCaml-LGPL-linking-exception',
    '// @generated by tools/why3_oracle/generate_z3_profile_tables.mjs; do not edit.',
    '',
    '///|',
    `fn generated_z3_profile_${suffix}() -> Array[Bytes] {`,
    '  [',
    ...literals.map(literal => `    ${literal},`),
    '  ]',
    '}',
    '',
  ].join('\n'));
}

function outputs(profile) {
  const result = new Map();
  const functions = [];
  for (let offset = 0, index = 0; offset < profile.length;
    offset += CHUNK_BYTES, index += 1) {
    const suffix = String(index).padStart(2, '0');
    result.set(`generated_profile_${suffix}.mbt`,
      shardSource(index, profile.subarray(offset, offset + CHUNK_BYTES)));
    functions.push(`generated_z3_profile_${suffix}`);
  }
  result.set('generated_profile_index.mbt', Buffer.from([
    '// SPDX-License-Identifier: LGPL-2.1-only WITH OCaml-LGPL-linking-exception',
    '// @generated by tools/why3_oracle/generate_z3_profile_tables.mjs; do not edit.',
    '',
    '///|',
    'fn generated_z3_profile_shards() -> Array[Array[Bytes]] {',
    '  [',
    ...functions.map(name => `    ${name}(),`),
    '  ]',
    '}',
    '',
  ].join('\n')));
  return result;
}

function managed(directory) {
  return readdirSync(directory)
    .filter(name => /^generated_profile_(?:\d\d|index)\.mbt$/u.test(name))
    .sort();
}

export function main(argv = process.argv.slice(2)) {
  try {
    const options = parseArguments(argv);
    const expected = outputs(readFileSync(options.profile));
    const names = [...expected.keys()].sort();
    if (options.mode === 'output') {
      mkdirSync(options.directory, { recursive: true });
      const stale = managed(options.directory).filter(name => !expected.has(name));
      if (stale.length > 0) fail(`stale generated profile files: ${stale.join(', ')}`);
      for (const [name, bytes] of expected) writeFileSync(join(options.directory, name), bytes);
    } else {
      const actualNames = managed(options.directory);
      if (JSON.stringify(actualNames) !== JSON.stringify(names)) fail('generated profile file set drift');
      for (const [name, bytes] of expected) {
        if (!readFileSync(join(options.directory, name)).equals(bytes)) fail(`${name} drift`);
      }
    }
  } catch (error) {
    process.stderr.write(`generate_z3_profile_tables: ${error.message}\n`);
    process.exitCode = 1;
  }
}

if (process.argv[1] !== undefined &&
    resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
